// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ViagensWebApi.Context;

#nullable disable

namespace ViagensWebApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20221104174009_1")]
    partial class _1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ViagensWebApi.Models.Destino", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Localidade")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)");

                    b.Property<string>("Proprietario")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)");

                    b.Property<string>("Valor")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)");

                    b.HasKey("Id");

                    b.ToTable("Destinos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Localidade = "Portugual",
                            Nome = "Aveiro",
                            Proprietario = "Bernardo",
                            Valor = "4.000,00"
                        },
                        new
                        {
                            Id = 2,
                            Localidade = "Portugual",
                            Nome = "Porto",
                            Proprietario = "Maria",
                            Valor = "3.000,00"
                        },
                        new
                        {
                            Id = 3,
                            Localidade = "Portugual",
                            Nome = "Leiria",
                            Proprietario = "Marcos",
                            Valor = "2.000,00"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
